apiVersion: v1
kind: Pod
metadata:
  labels:
    fuse.serverful.fluid.io/inject: "true"
    fluid.io/dataset.vineyard.sched: required
  name: app
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 3600
    image: python:3.10
    imagePullPolicy: IfNotPresent
    name: app
    volumeMounts:
    - mountPath: /data
      name: vineyard-vol
  volumes:
  - name: vineyard-vol
    persistentVolumeClaim:
      claimName: vineyard