apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: machine-learning-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.0, pipelines.kubeflow.org/pipeline_compilation_time: '2024-01-16T20:04:59.556095',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "An example pipeline that
      trains and logs a regression model.", "inputs": [{"name": "data_multiplier",
      "type": "Integer"}, {"name": "registry", "type": "String"}], "name": "Machine
      Learning Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.0}
spec:
  entrypoint: machine-learning-pipeline
  templates:
  - name: machine-learning-pipeline
    inputs:
      parameters:
      - {name: data_multiplier}
      - {name: registry}
    dag:
      tasks:
      - name: preprocess-data
        template: preprocess-data
        arguments:
          parameters:
          - {name: data_multiplier, value: '{{inputs.parameters.data_multiplier}}'}
          - {name: registry, value: '{{inputs.parameters.registry}}'}
      - name: test-data
        template: test-data
        dependencies: [train-data]
        arguments:
          parameters:
          - {name: registry, value: '{{inputs.parameters.registry}}'}
      - name: train-data
        template: train-data
        dependencies: [preprocess-data]
        arguments:
          parameters:
          - {name: registry, value: '{{inputs.parameters.registry}}'}
  - name: preprocess-data
    container:
      args: ['--data_multiplier={{inputs.parameters.data_multiplier}}', --with_vineyard=True]
      command: [python3, preprocess.py]
      image: '{{inputs.parameters.registry}}/preprocess-data'
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - {mountPath: /data, name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4}
      - {mountPath: /vineyard/client/config, name: pvolume-d7f6fa616076983e0a6a1242a1945f9c18fb44256cdfffaad45ddd9}
    inputs:
      parameters:
      - {name: data_multiplier}
      - {name: registry}
    metadata:
      labels:
        fuse.serverful.fluid.io/inject: "true"
        fluid.io/dataset.vineyard.sched: required
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.0
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: pvolume-d7f6fa616076983e0a6a1242a1945f9c18fb44256cdfffaad45ddd9
      persistentVolumeClaim: {claimName: vineyard}
    - name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4
      persistentVolumeClaim: {claimName: benchmark-data}
  - name: test-data
    container:
      args: [--with_vineyard=True]
      command: [python3, test.py]
      image: '{{inputs.parameters.registry}}/test-data'
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - {mountPath: /data, name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4}
      - {mountPath: /vineyard/client/config, name: pvolume-d7f6fa616076983e0a6a1242a1945f9c18fb44256cdfffaad45ddd9}
    inputs:
      parameters:
      - {name: registry}
    metadata:
      labels:
        fuse.serverful.fluid.io/inject: "true"
        fluid.io/dataset.vineyard.sched: required
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.0
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: pvolume-d7f6fa616076983e0a6a1242a1945f9c18fb44256cdfffaad45ddd9
      persistentVolumeClaim: {claimName: vineyard}
    - name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4
      persistentVolumeClaim: {claimName: benchmark-data}
  - name: train-data
    container:
      args: [--with_vineyard=True]
      command: [python3, train.py]
      image: '{{inputs.parameters.registry}}/train-data'
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - {mountPath: /data, name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4}
      - {mountPath: /vineyard/client/config, name: pvolume-d7f6fa616076983e0a6a1242a1945f9c18fb44256cdfffaad45ddd9}
    inputs:
      parameters:
      - {name: registry}
    metadata:
      labels:
        fuse.serverful.fluid.io/inject: "true"
        fluid.io/dataset.vineyard.sched: required
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.0
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: pvolume-d7f6fa616076983e0a6a1242a1945f9c18fb44256cdfffaad45ddd9
      persistentVolumeClaim: {claimName: vineyard}
    - name: pvolume-d9c6725a1237b14c08a2567cb12c489bec539873deeddba7d87f5b4
      persistentVolumeClaim: {claimName: benchmark-data}
  arguments:
    parameters:
    - {name: data_multiplier}
    - {name: registry}
  serviceAccountName: pipeline-runner
