# Copyright 2020-2023 Alibaba Group Holding Limited.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ template "vineyard.fullname" . }}
    role: etcd
    etcd_node: {{ template "vineyard.fullname" . }}-etcd
  name: {{ template "vineyard.fullname" . }}-etcd
  ownerReferences:
  {{- if .Values.owner.enabled }}
  - apiVersion: {{ .Values.owner.apiVersion }}
    blockOwnerDeletion: {{ .Values.owner.blockOwnerDeletion }}
    controller: {{ .Values.owner.controller }}
    kind: {{ .Values.owner.kind }}
    name: {{ .Values.owner.name }}
    uid: {{ .Values.owner.uid }}
  {{- end }}
spec:
  containers:
  - name: etcd
    image: vineyardcloudnative/vineyardd:latest
    imagePullPolicy: IfNotPresent
    command:
    - etcd
    - --name
    - {{ template "vineyard.fullname" . }}-etcd
    - --initial-advertise-peer-urls
    - http://{{ template "vineyard.fullname" . }}-etcd:2380
    - --advertise-client-urls
    - http://{{ template "vineyard.fullname" . }}-etcd:2379
    - --listen-peer-urls
    - http://0.0.0.0:2380
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --initial-cluster
    - {{ template "vineyard.fullname" . }}-etcd=http://{{ template "vineyard.fullname" . }}-etcd:2380
    - --initial-cluster-state
    - new
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: server
      protocol: TCP
  restartPolicy: Always