apiVersion: v1
kind: Pod
metadata:
  labels:
    fuse.serverful.fluid.io/inject: "true"
    fluid.io/dataset.vineyard.sched: required
  name: application
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - |
      pip install vineyard numpy pandas;
      cat << EOF >> application.py
      import vineyard;
      import numpy as np;
      import pandas as pd;
      client = vineyard.connect("/data/vineyard.sock");
      # put a pandas dataframe to vineyard
      client.put(pd.DataFrame(np.random.randn(100, 4), columns=list('ABCD')), persist=True, name="test_dataframe");
      # put a basic data unit to vineyard
      client.put((1, 1.2345, 'xxxxabcd'), persist=True, name="test_basic_data_unit");
      client.close()
      EOF
      python application.py;
      sleep infinity;
    image: python:3.10
    imagePullPolicy: IfNotPresent
    name: application
    volumeMounts:
    - mountPath: /data
      name: vineyard-vol
  volumes:
  - name: vineyard-vol
    persistentVolumeClaim:
      claimName: vineyard
